### ISSUE TITLE
Search does not search locations

### ISSUE THREAD

**Issue by garie** [bencentra/csh-map#14]
The search bar doesn't let you search for a location and zoom/center the map. I expected to be able to type in Mountain View, CA and it would refocus the map on Mountain View. The search appears to only look at names and usernames.

**Comment by bencentra** [comment]
Moved the search bar to a modal window. You can now select which type of search to make: names or locations. Location results may vary, depends on how specific users got when adding themselves to the map.
![screen shot 2015-01-14 at 8 43 29 am](https://cloud.githubusercontent.com/assets/517104/5739609/7093579a-9bc9-11e4-8419-5dc6df606b96.png)
