### ISSUE TITLE
 Last Updated: Invalid Date

### ISSUE THREAD

**Issue by agargiulo** [bencentra/csh-map#18]
The boxes that show up when you click on a pin have the text " Last Updated: Invalid Date" instead of an actual date.

**Comment by bencentra** [comment]
Can you post a screenshot with an example? I did a quick spot check and I didn't see any.

**Comment by agargiulo** [comment]
![screen shot 2015-02-03 at 13 28 28](https://cloud.githubusercontent.com/assets/769543/6026407/96a30bf8-aba8-11e4-8327-719c2327662c.png)

**Comment by agargiulo** [comment]
It appears that after you update your location now it fixes itself.
